#!/usr/bin/env ruby

require_relative 'git_utils.rb'

%w[master clean].each{|branch| exit_if_on_the_branch branch}

current_time = Time.now
new_branch_name = current_time.strftime("%Y%m%d%H%M%S%3N")
run_git_command 'add -A'
run_git_command 'commit -m "Committing"'

checkout('clean')
exit_if_not_on_the_branch 'clean'

checkout(new_branch_name)
run_git_command("pull jp master")
puts "new branch name:#{new_branch_name}"

